# This file was generated by GoReleaser. DO NOT EDIT.
cask "odlang" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "73ef496c5b5158c6cf8eb70b386ed964f4fb8ae654e9a938640f840be4bb7b5b"
      url "https://github.com/Sameetpatro/odlang/releases/download/v#{version}/od_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8848598b88a3ed23a1670d5aa95db4c9379f4530358ea4d3e97478ef048ca620"
      url "https://github.com/Sameetpatro/odlang/releases/download/v#{version}/od_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8be150fd719a36eddf4ab1f8d1fdc6874d7a8865ad1631b7306d27f9c4854a17"
      url "https://github.com/Sameetpatro/odlang/releases/download/v#{version}/od_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "76fb99ae24f5e9f67ef77f30fffdf1b00f6a8689174c97f81c6510c934d7dcd4"
      url "https://github.com/Sameetpatro/odlang/releases/download/v#{version}/od_#{version}_linux_arm64.tar.gz"
    end
  end

  name "odlang"
  desc "OdLang — a programming language with Odia-inspired keywords"
  homepage "https://github.com/Sameetpatro/odlang"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "od"

  # No zap stanza required

end
