# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odlang < Formula
  desc "OdLang — a programming language with Odia-inspired keywords"
  homepage "https://github.com/Sameetpatro/odlang"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sameetpatro/odlang/releases/download/v0.1.6/od_0.1.6_darwin_amd64.tar.gz"
      sha256 "7fc8710af1428b64a85a050f56366932d3c652a2d2433d9e27b2167e0c69b9a3"

      define_method(:install) do
        bin.install "odlang"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sameetpatro/odlang/releases/download/v0.1.6/od_0.1.6_darwin_arm64.tar.gz"
      sha256 "f0770e182a5fe24d53d92060aaf7a88e52abac13edcc59def688aa11f403af16"

      define_method(:install) do
        bin.install "odlang"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sameetpatro/odlang/releases/download/v0.1.6/od_0.1.6_linux_amd64.tar.gz"
      sha256 "efdb46c723e7de3768d7395c051810ecc585c66f36fa87614b5eec560df38c04"
      define_method(:install) do
        bin.install "odlang"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sameetpatro/odlang/releases/download/v0.1.6/od_0.1.6_linux_arm64.tar.gz"
      sha256 "bfae128c5e21c58d364279283ee5c2229cf8faa1c06994abd75149014ab65506"
      define_method(:install) do
        bin.install "odlang"
      end
    end
  end

  test do
    system "#{bin}/odlang", "version"
  end
end
