# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odlang < Formula
  desc "OdLang — a programming language with Odia-inspired keywords"
  homepage "https://github.com/Sameetpatro/odlang"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sameetpatro/odlang/releases/download/v0.1.5/od_0.1.5_darwin_amd64.tar.gz"
      sha256 "7074b26af327753191dbba672c35690c3d8516c9d70ed62e297f6d232df87cb8"

      define_method(:install) do
        bin.install "od"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sameetpatro/odlang/releases/download/v0.1.5/od_0.1.5_darwin_arm64.tar.gz"
      sha256 "288b69de3d24a88c2e15de4710749fd438edec2548726edb8dec2e36f67a8ba3"

      define_method(:install) do
        bin.install "od"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sameetpatro/odlang/releases/download/v0.1.5/od_0.1.5_linux_amd64.tar.gz"
      sha256 "8f76ff45951ca7f63840b8dbe668e8a75aee1d1fc5589e10d1aca571c97eabf2"
      define_method(:install) do
        bin.install "od"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Sameetpatro/odlang/releases/download/v0.1.5/od_0.1.5_linux_arm64.tar.gz"
      sha256 "212f75b7c019de0fcc01b67533ffbcb6584ef79e7380abee14a02955bdca9ec3"
      define_method(:install) do
        bin.install "od"
      end
    end
  end

  test do
    system "#{bin}/od", "version"
  end
end
